from __future__ import annotations

from collections.abc import Iterable
from typing import Any

from disnake.ext import commands

_LANGUAGE_TRANSLATIONS: dict[str, dict[str, str]] = {
    "es": {
        "help": "ayuda",
        "language": "idioma",
        "settings": "ajustes",
        "setprefix": "prefijo",
        "setstatus": "estado",
        "ping": "latencia",
        "botinfo": "infobot",
        "serverinfo": "infoservidor",
        "userinfo": "infousuario",
        "runtime": "ejecucion",
        "avatar": "perfil",
        "poll": "encuesta",
        "purge": "limpiar",
        "kick": "expulsar",
        "ban": "banear",
        "unban": "desbanear",
        "tempban": "bantemporal",
        "timeout": "silencio",
        "untimeout": "quitasilencio",
        "warn": "advertir",
        "warnings": "advertencias",
        "music": "musica",
        "welcome": "bienvenida",
        "security": "seguridad",
        "acl": "acceso",
        "ticket": "ticketes",
        "automod": "automoderacion",
        "reactionrole": "rolreaccion",
        "announce": "anuncios",
        "analytics": "analitica",
        "math": "matematicas",
        "text": "texto",
        "tools": "herramientas",
        "status": "estado",
        "set": "establecer",
        "join": "unir",
        "leave": "salir",
        "play": "reproducir",
        "pause": "pausar",
        "resume": "continuar",
        "skip": "saltar",
        "stop": "detener",
        "queue": "cola",
        "volume": "volumen",
        "nowplaying": "sonando",
        "info": "informacion",
        "setchannel": "canal",
        "message": "mensaje",
        "enable": "activar",
        "disable": "desactivar",
        "preview": "vista",
        "configure": "configurar",
        "antinuke": "antiraid",
        "allow": "permitir",
        "revoke": "revocar",
        "list": "lista",
        "open": "abrir",
        "close": "cerrar",
        "escalate": "escalar",
        "transcript": "transcripcion",
        "add": "agregar",
        "remove": "quitar",
        "toggle": "alternar",
        "bind": "vincular",
        "unbind": "desvincular",
        "create": "crear",
        "runnow": "ahora",
        "topcommands": "topcomandos",
        "topusers": "topusuarios",
        "sub": "restar",
        "mul": "multiplicar",
        "div": "dividir",
        "mod": "modulo",
        "pow": "potencia",
        "sqrt": "raiz",
        "abs": "absoluto",
        "ceil": "techo",
        "floor": "piso",
        "round": "redondear",
        "max": "maximo",
        "min": "minimo",
        "avg": "promedio",
        "sum": "suma",
        "clamp": "limitar",
        "percent": "porcentaje",
        "bmi": "imc",
        "upper": "mayus",
        "lower": "minus",
        "title": "titulo",
        "reverse": "inverso",
        "length": "longitud",
        "words": "palabras",
        "replace": "reemplazar",
        "trim": "recortar",
        "repeat": "repetir",
        "prefix": "prefijo",
        "suffix": "sufijo",
        "count": "contar",
        "startswith": "empieza",
        "endswith": "termina",
        "contains": "contiene",
        "split": "separar",
        "coinflip": "moneda",
        "roll": "dado",
        "choose": "elegir",
        "random": "aleatorio",
        "uuid": "identificador",
        "timestamp": "marca",
        "unixnow": "unixahora",
        "base64encode": "base64cod",
        "base64decode": "base64dec",
        "urlencode": "urlcod",
        "urldecode": "urldec",
        "md5": "md5hash",
        "sha1": "sha1hash",
        "sha256": "sha256hash",
        "colorhex": "colorhex",
        "jsonpretty": "jsonbonito",
    },
    "fr": {
        "help": "aide",
        "language": "langue",
        "settings": "reglages",
        "setprefix": "defprefixe",
        "setstatus": "defstatut",
        "ping": "latence",
        "botinfo": "infobot",
        "serverinfo": "infoserveur",
        "userinfo": "infoutilisateur",
        "runtime": "duree",
        "avatar": "profil",
        "poll": "sondage",
        "purge": "nettoyer",
        "kick": "expulser",
        "ban": "bannir",
        "unban": "debannir",
        "tempban": "bantemp",
        "timeout": "muet",
        "untimeout": "demuet",
        "warn": "avertir",
        "warnings": "avertissements",
        "music": "musique",
        "welcome": "bienvenue",
        "security": "securite",
        "acl": "acces",
        "ticket": "ticket",
        "automod": "automod",
        "reactionrole": "rolereaction",
        "announce": "annonce",
        "analytics": "analyse",
        "math": "maths",
        "text": "texte",
        "tools": "outils",
        "status": "statut",
        "set": "definir",
        "join": "rejoindre",
        "leave": "quitter",
        "play": "lire",
        "pause": "pause",
        "resume": "reprendre",
        "skip": "passer",
        "stop": "arreter",
        "queue": "file",
        "volume": "volume",
        "nowplaying": "encours",
        "info": "infos",
        "setchannel": "salon",
        "message": "message",
        "enable": "activer",
        "disable": "desactiver",
        "preview": "apercu",
        "configure": "configurer",
        "antinuke": "antiraid",
        "allow": "autoriser",
        "revoke": "retirer",
        "list": "liste",
        "open": "ouvrir",
        "close": "fermer",
        "escalate": "escalader",
        "transcript": "transcript",
        "add": "ajouter",
        "remove": "supprimer",
        "toggle": "basculer",
        "bind": "lier",
        "unbind": "delier",
        "create": "creer",
        "runnow": "maintenant",
        "topcommands": "topcommandes",
        "topusers": "toputilisateurs",
        "sub": "soustraire",
        "mul": "multiplier",
        "div": "diviser",
        "mod": "modulo",
        "pow": "puissance",
        "sqrt": "racine",
        "abs": "absolu",
        "ceil": "plafond",
        "floor": "sol",
        "round": "arrondir",
        "max": "maximum",
        "min": "minimum",
        "avg": "moyenne",
        "sum": "somme",
        "clamp": "borner",
        "percent": "pourcentage",
        "bmi": "imc",
        "upper": "majuscule",
        "lower": "minuscule",
        "title": "titre",
        "reverse": "inverse",
        "length": "longueur",
        "words": "mots",
        "replace": "remplacer",
        "trim": "rogner",
        "repeat": "repeter",
        "prefix": "prefixe",
        "suffix": "suffixe",
        "count": "compter",
        "startswith": "commence",
        "endswith": "termine",
        "contains": "contient",
        "split": "separer",
        "coinflip": "piece",
        "roll": "de",
        "choose": "choisir",
        "random": "aleatoire",
        "uuid": "identifiant",
        "timestamp": "horodatage",
        "unixnow": "unixmaintenant",
        "base64encode": "base64coder",
        "base64decode": "base64decoder",
        "urlencode": "urlcoder",
        "urldecode": "urldecoder",
        "md5": "md5hachage",
        "sha1": "sha1hachage",
        "sha256": "sha256hachage",
        "colorhex": "couleurhex",
        "jsonpretty": "jsonpropre",
    },
    "de": {
        "help": "hilfe",
        "language": "sprache",
        "settings": "einstellungen",
        "setprefix": "prefixsetzen",
        "setstatus": "statussetzen",
        "ping": "latenz",
        "botinfo": "botinfo",
        "serverinfo": "serverinfo",
        "userinfo": "nutzerinfo",
        "runtime": "laufzeit",
        "avatar": "profilbild",
        "poll": "umfrage",
        "purge": "saeubern",
        "kick": "werfen",
        "ban": "sperren",
        "unban": "entsperren",
        "tempban": "zeitsperre",
        "timeout": "stumm",
        "untimeout": "entstumm",
        "warn": "warnen",
        "warnings": "warnungen",
        "music": "musik",
        "welcome": "willkommen",
        "security": "sicherheit",
        "acl": "zugriff",
        "ticket": "ticket",
        "automod": "automod",
        "reactionrole": "reaktionsrolle",
        "announce": "ankuendigen",
        "analytics": "analyse",
        "math": "mathe",
        "text": "text",
        "tools": "werkzeuge",
        "status": "status",
        "set": "setzen",
        "join": "beitreten",
        "leave": "verlassen",
        "play": "spielen",
        "pause": "pausieren",
        "resume": "fortsetzen",
        "skip": "ueberspringen",
        "stop": "stoppen",
        "queue": "warteschlange",
        "volume": "lautstaerke",
        "nowplaying": "jetzt",
        "info": "info",
        "setchannel": "kanalsetzen",
        "message": "nachricht",
        "enable": "aktivieren",
        "disable": "deaktivieren",
        "preview": "vorschau",
        "configure": "konfigurieren",
        "antinuke": "antiraid",
        "allow": "erlauben",
        "revoke": "widerrufen",
        "list": "liste",
        "open": "oeffnen",
        "close": "schliessen",
        "escalate": "eskalieren",
        "transcript": "protokoll",
        "add": "hinzufuegen",
        "remove": "entfernen",
        "toggle": "umschalten",
        "bind": "binden",
        "unbind": "loesen",
        "create": "erstellen",
        "runnow": "jetztstart",
        "topcommands": "topbefehle",
        "topusers": "topnutzer",
        "sub": "subtrahieren",
        "mul": "multiplizieren",
        "div": "teilen",
        "mod": "rest",
        "pow": "potenz",
        "sqrt": "wurzel",
        "abs": "betrag",
        "ceil": "aufrunden",
        "floor": "abrunden",
        "round": "runden",
        "max": "maximum",
        "min": "minimum",
        "avg": "durchschnitt",
        "sum": "summe",
        "clamp": "begrenzen",
        "percent": "prozent",
        "bmi": "bmi",
        "upper": "gross",
        "lower": "klein",
        "title": "titel",
        "reverse": "umkehren",
        "length": "laenge",
        "words": "woerter",
        "replace": "ersetzen",
        "trim": "kuerzen",
        "repeat": "wiederholen",
        "prefix": "prefix",
        "suffix": "suffix",
        "count": "zaehlen",
        "startswith": "beginntmit",
        "endswith": "endetmit",
        "contains": "enthaelt",
        "split": "teilenbei",
        "coinflip": "muenzwurf",
        "roll": "wuerfeln",
        "choose": "waehlen",
        "random": "zufall",
        "uuid": "kennung",
        "timestamp": "zeitstempel",
        "unixnow": "unixjetzt",
        "base64encode": "base64kodieren",
        "base64decode": "base64dekodieren",
        "urlencode": "urlkodieren",
        "urldecode": "urldekodieren",
        "md5": "md5hash",
        "sha1": "sha1hash",
        "sha256": "sha256hash",
        "colorhex": "farbhex",
        "jsonpretty": "jsonformatiert",
    },
    "ru": {
        "help": "pomosh",
        "language": "yazyk",
        "settings": "nastroiki",
        "setprefix": "prefiks",
        "setstatus": "statusset",
        "ping": "pingru",
        "botinfo": "botinform",
        "serverinfo": "serverinform",
        "userinfo": "userinform",
        "runtime": "vremyaraboty",
        "avatar": "avatarru",
        "poll": "opros",
        "purge": "ochistit",
        "kick": "kik",
        "ban": "ban",
        "unban": "razban",
        "tempban": "vremenban",
        "timeout": "mut",
        "untimeout": "razmut",
        "warn": "pred",
        "warnings": "predy",
        "music": "muzyka",
        "welcome": "privetstvie",
        "security": "bezopasnost",
        "acl": "dostup",
        "ticket": "tiket",
        "automod": "avtomod",
        "reactionrole": "reakciyarol",
        "announce": "obyava",
        "analytics": "analitika",
        "math": "matematika",
        "text": "tekst",
        "tools": "instrumenty",
        "status": "sostoyanie",
        "set": "ustanovit",
        "join": "voiti",
        "leave": "vyiti",
        "play": "igrat",
        "pause": "pauza",
        "resume": "prodolzhit",
        "skip": "propusk",
        "stop": "ostanovit",
        "queue": "ochered",
        "volume": "gromkost",
        "nowplaying": "seichas",
        "info": "info",
        "setchannel": "kanal",
        "message": "soobshenie",
        "enable": "vklyuchit",
        "disable": "vyklyuchit",
        "preview": "predprosmotr",
        "configure": "nastroit",
        "antinuke": "antireid",
        "allow": "razreshit",
        "revoke": "otozvat",
        "list": "spisok",
        "open": "otkryt",
        "close": "zakryt",
        "escalate": "eskalaciya",
        "transcript": "stenogramma",
        "add": "dobavit",
        "remove": "ubrat",
        "toggle": "perekluchit",
        "bind": "privyazat",
        "unbind": "otvyazat",
        "create": "sozdat",
        "runnow": "seichass",
        "topcommands": "topkomandy",
        "topusers": "topyuzery",
        "sub": "vychest",
        "mul": "umnozhit",
        "div": "delit",
        "mod": "ostatok",
        "pow": "stepen",
        "sqrt": "koren",
        "abs": "modul",
        "ceil": "verh",
        "floor": "niz",
        "round": "okruglit",
        "max": "maks",
        "min": "min",
        "avg": "srednee",
        "sum": "summa",
        "clamp": "ogranichit",
        "percent": "procent",
        "bmi": "imt",
        "upper": "verhreg",
        "lower": "nizreg",
        "title": "zagolovok",
        "reverse": "naoborot",
        "length": "dlina",
        "words": "slova",
        "replace": "zamenit",
        "trim": "obrezat",
        "repeat": "povtor",
        "prefix": "prefiks",
        "suffix": "suffiks",
        "count": "schet",
        "startswith": "nachinaetsya",
        "endswith": "zakanchivaetsya",
        "contains": "soderzhit",
        "split": "razdelit",
        "coinflip": "monetka",
        "roll": "brosok",
        "choose": "vybor",
        "random": "sluchaino",
        "uuid": "ident",
        "timestamp": "vremyametka",
        "unixnow": "unixseichas",
        "base64encode": "b64kod",
        "base64decode": "b64dekod",
        "urlencode": "urlkod",
        "urldecode": "urldekod",
        "md5": "md5ru",
        "sha1": "sha1ru",
        "sha256": "sha256ru",
        "colorhex": "hexcvet",
        "jsonpretty": "jsonkrasivo",
    },
}


def command_aliases_for(command_name: str) -> list[str]:
    """Return translated aliases across supported non-English locales."""
    normalized = command_name.lower().strip()
    aliases: list[str] = []
    for language in ("es", "fr", "de", "ru"):
        translated = _LANGUAGE_TRANSLATIONS.get(language, {}).get(normalized)
        if translated is None:
            continue
        candidate = translated.lower().strip()
        if candidate and candidate != normalized and candidate not in aliases:
            aliases.append(candidate)
    return aliases


def _registry_for_command(
    bot: commands.Bot,
    command: commands.Command[Any, Any, Any],
) -> dict[str, commands.Command[Any, Any, Any]]:
    parent = command.parent
    if isinstance(parent, commands.Group):
        return parent.all_commands
    return bot.all_commands


def _register_command_aliases(
    bot: commands.Bot,
    command: commands.Command[Any, Any, Any],
) -> int:
    added = 0
    registry = _registry_for_command(bot, command)
    for alias in command_aliases_for(command.name):
        existing = registry.get(alias)
        if existing is not None and existing is not command:
            continue
        if alias not in command.aliases:
            command.aliases = [*command.aliases, alias]
        if existing is None:
            registry[alias] = command
            added += 1
    if isinstance(command, commands.Group):
        for subcommand in command.commands:
            added += _register_command_aliases(bot, subcommand)
    return added


def register_multilingual_aliases(
    bot: commands.Bot,
    root_command_names: Iterable[str],
) -> int:
    """Register translated aliases for selected command trees."""
    added = 0
    for root_name in root_command_names:
        command = bot.get_command(root_name)
        if command is None:
            continue
        added += _register_command_aliases(bot, command)
    return added
